name = "order-discount-rust"
type = "order_discounts"
api_version = "2022-07"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/order-discount-rust.wasm"

[ui.paths]
create = "/discount/bc600f96-2f89-4a7c-bb36-83b544d8b0bd/new"
details = "/discount/bc600f96-2f89-4a7c-bb36-83b544d8b0bd/:id"

[input.variables]
namespace = "$app:polyglot-functions"
key = "function-configuration"