name = "order-discount-assemblyscript"
type = "order_discounts"
api_version = "2022-07"

[build]
command = "bash build.sh"
path = "build/release.wasm"

[ui.paths]
create = "/discount/01GE2WRX1BWC5P3VP37AVXY5BW/new"
details = "/discount/01GE2WRX1BWC5P3VP37AVXY5BW/:id"
