name = "order-discount-cpp"
type = "order_discounts"
api_version = "2023-01"

[build]
command = "bash build.sh"
path = "build/main.wasm"

[ui.paths]
create = "/discount/:functionId/new"
details = "/discount/:functionId/:id"

[input.variables]
namespace = "$app:polyglot-functions"
key = "function-configuration"