name = "order-discount-javascript"
type = "order_discounts"
api_version = "2023-01"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/discount/:functionId/new"
details = "/discount/:functionId/:id"

[input.variables]
namespace = "$app:polyglot-functions"
key = "function-configuration"